### ISSUE TITLE
Create function: extract_prevalent_diabetes()

### ISSUE THREAD

**Issue by Aastedet** [steno-aarhus/osdc#13]
A function that takes the output of create_diabetes_cohort() and filters it to only individuals with prevalent diabetes: individuals with diabetes diagnosed prior to a specified index date who are also alive one this specified index date.

Also re-classifies diabetes type depending on insulin purchases in the year prior to the index date (very few individuals - we could potentially discuss with stakeholders whether to omit this in the future).

**Comment by lwjohnst86** [comment]
These issues are outdated, and replaced by others now
