### ISSUE TITLE
The "honuge" variable in the fake health service data should be formatted as a 4-digit string

### ISSUE THREAD

**Issue by Aastedet** [steno-aarhus/osdc#134]
Right now it looks like any initial zeroes are removed, so I assume it's a int or dbl (see data-sources.html)

**Comment by signekb** [comment]
Oh, havn't I fixed this in #165 ?

**Comment by Aastedet** [comment]
> Oh, havn't I fixed this in #165 ? I'm adding the simulated data to our targets pipeline in #167 and rerunning it there. Shouldn't that fix the issue? Or is this a separate thing?

It's a separate thing, I think. You can test it by running `simulate-data.Rmd`, looking at the `register_data` object's `honuge` values (has leading 0s), and then loading `data/register_data.rda` (leading zeros are gone).

**Comment by Aastedet** [comment]
On further thought: That might actually fix it... the `speciale` variable has nicely preserved leading 0s, so the saving to Rda is working fine. The simulated data has probably just been last saved while `honuge` was formatted as an integer/numeric.
