### ISSUE TITLE
Document `join()` functions

### ISSUE THREAD

**Issue by signekb** [steno-aarhus/osdc#140]

**Comment by signekb** [comment]
Reassigning to Anders bc he feels it makes sense for him to go through it before detailing the `include_diabetes_diagnoses()` function

**Comment by Aastedet** [comment]
Links to previous comments for my own convenience:
[get_diabetes_type()](https://github.com/steno-aarhus/osdc/pull/133#discussion_r1891345550)
[get_diagnosis_date()](https://github.com/steno-aarhus/osdc/pull/133#discussion_r1891373400)
