### ISSUE TITLE
Function to list all registers needed as well as all variables needed

### ISSUE THREAD

**Issue by lwjohnst86** [steno-aarhus/osdc#16]
So that it is very explicit, in order for this algorithm to work, the user needs THESE registers and THESE variables.

**Comment by Aastedet** [comment]
Rought draft (copy/paste from an old email in Danish):
This is for the original implementation. Some of the these variables are no longer needed (they have minimal impact, but perhaps we should keep them for reproducibility's sake - that's for a later discussion):

Fra CPR-registerets bef-tabel:
PNR: Patient-ID
KOEN: Køn/sex
FOED_DATO: Date of birth

Fra Lægemiddelstatistikregisteret:
PNR: Patient-ID
EKSD: Ekspeditionsdato
APK: Antal pakker købt
INDO: Indikationskode på recepten (kan udelades, gør stort set ingen forskel, men det kræver at man lige fjerner nogle få linjers kode et sted i scriptet)
NAME: Præparatnavn
ATC: Præparatets ATC-kode 
VOLUME: Antal daglige standarddoser indeholdt i pakken
 
Fra Landspatientregisteret:
Fra lpr_adm:
PNR: Patient-ID
RECNUM: Kontakt-ID
C_ADIAG: Kontaktens A-diagnose (kan udelades, hvis man bare i stedet tager den fra C_DIAG- og C_DIAGTYPE-variablerne i lpr_diag-tabellen)
C_BLOK: Specialeblok som kontaktens afdeling tilhører.
C_PATTYPE: Patientens kontakt-type
C_SPEC: Speciale som kontaktens afdelingen tilhører.
D_INDDTO: Dato for starten på kontakten.
 
Fra lpr_diag:
RECNUM: Kontakt-ID
C_DIAG: Diagnose
C_DIAGTYPE: Diagnosens type.
 
Fra Sygesikringsregisteret:
PNR: Patient-ID
BARNMAK: Barnemarkering
SPECIALE: Ydelsens specialekode
HONAAR: Honoreringsår for ydelsen
HONUGE: Honoreringsuge for ydelsen
 
Fra Laboratoriedatabasens Forskertabel (hvis HbA1c skal bruges til inklusion):
PATIENT_CPR: Patient-ID
SAMPLINGDATE: Dato for prøvetagningen
ANALYSISCODE: Analysens NPU-kode
VALUE: Værdi af analysens resultat
