### ISSUE TITLE
Is `honuge` formatted `wwyy` or `yyww`? 

### ISSUE THREAD

**Issue by signekb** [steno-aarhus/osdc#160]
In the [simulation definition](https://github.com/steno-aarhus/osdc/blob/main/data-raw/simulation-definitions.csv) it says `wwyy` as well as in the [function-flow in #133](https://github.com/steno-aarhus/osdc/pull/133/files#): 
> [...] generate a proper date variable based on the year-week (wwyy-formatted) variable (`honuge`)

However, on [Denmark's statistics](https://www.dst.dk/da/TilSalg/Forskningsservice/Dokumentation/hoejkvalitetsvariable/sygesikring---ydelser/honuge) (if I'm looking the right place), says `yyww` (or `ÅÅUU`). 

What say you, @Aastedet ?

**Comment by Aastedet** [comment]
Just double-checked the date, and you / DST are correct: it is yyww

**Comment by signekb** [comment]
Thanks for checking 🚀
