### ISSUE TITLE
Create function: filter_diags()

### ISSUE THREAD

**Issue by Aastedet** [steno-aarhus/osdc#6]
A function to filter necessary diagnoses from lpr_adm and lpr_diag to create the diabetes cohort with create_diabetes_cohort()

One of four filtering functions - the other three being filter_meds(), filter_hba1c() and filter_services().

At a point we may have to address differences between LPR2 and LPR3 data, unless we delegate that to the users' preprocessing of raw data.

**Comment by signekb** [comment]
This is an outdated issue. I have created a new one based on the functions we have described in the functionality flow and will move the relevant information in this issue to that issue #91
