### ISSUE TITLE
Discussion: osdc vs OSDC?

### ISSUE THREAD

**Issue by lwjohnst86** [steno-aarhus/osdc#61]
@Aastedet Should we name call the algorithm OSDC and package osdc or just use osdc throughout?

**Comment by Aastedet** [comment]
@lwjohnst86 @signekb I think it makes sense to refer to the package as lower-case (since nobody likes upper-case) and the algorithm itself in upper-case (it being an acronym). Unless that's confusing?

**Comment by lwjohnst86** [comment]
@Aastedet I'm fine with that!

**Comment by signekb** [comment]
Same 👍
