### ISSUE TITLE
Create function: filter_hba1c()

### ISSUE THREAD

**Issue by Aastedet** [steno-aarhus/osdc#8]
A function to filter diagnostic hemoglobin-a1c values from biomarker data to create the diabetes cohort with create_diabetes_cohort()

One of four filtering functions - the other three being filter_diags(), filter_meds() and filter_services().

If it doesn't already, the nationwide Register of Laboratory Results for Research should cover Central Denmark Region in the future, so we should design the function around that data structure (users supplementing with data from LABKA should preprocess it to match this structure).

**Comment by signekb** [comment]
This is an outdated issue. I have created a new one based on the functions we have described in the functionality flow and will move the relevant information in this issue to that issue #93
