### ISSUE TITLE
Reuse recnum and other variables between registers in fake data

### ISSUE THREAD

**Issue by lwjohnst86** [steno-aarhus/osdc#84]
We need to reuse the same vector of `recnum`s in both the `lpr_adm` + `lpr_diag` tables (and, similarly, reuse an `dw_ek_kontakt` vector for both LPR3 tables), similar to how the pnrs are the same in all the tables. Otherwise joining the tables using `recnum`/`dw_ek_kontakt`  as the joining key is going to be messy.

_Originally posted by @Aastedet in https://github.com/steno-aarhus/osdc/pull/70#discussion_r1585551339_

**Comment by Aastedet** [comment]
closes with #170
