### ISSUE TITLE
Look up and add actual vnr numbers

### ISSUE THREAD

**Issue by lwjohnst86** [steno-aarhus/osdc#85]
The vnr values for medications probably have to be hardcoded to match the real data/edge cases. I'll look them up and get back to you.

_Originally posted by @Aastedet in https://github.com/steno-aarhus/osdc/pull/70#discussion_r1585551339_

**Comment by Aastedet** [comment]
vnr values for Saxenda:
c(114620, 079356, 461535, 466374, 599897, 131577, 164108, 395175, 439932, 575140)
(taken from https://pro.medicin.dk/Medicin/Praeparater/7837#a380)

vnr values for Wegovy Flextouch:
c(164303, 178307, 418253, 431609, 448583, 396934, 534716, 538908, 560545, 058102, 131824, 191243, 394103, 405773, 066923, 187574, 191797, 409687, 437102, 153271, 178249, 386270, 468849)
(taken from https://pro.medicin.dk/Medicin/Praeparater/10247#a380)

New vnr numbers  are added as new drug packages are introduced, so this list may need updating in the future. It's not a regular occurence, so it's no big deal at this point.
www.pro.medicin.dk is a pretty stable website, so perhaps they can be scraped reliably from there.

I'll add the vnr values to a spreadsheet of data-values as part of #35

**Comment by lwjohnst86** [comment]
Closed in #109
