### ISSUE TITLE
Create function: filter_services()

### ISSUE THREAD

**Issue by Aastedet** [steno-aarhus/osdc#9]
A function to filter diabetes-specific podiatrist services from health service register data to create the diabetes cohort with create_diabetes_cohort()

One of four filtering functions - the other three being filter_diags(), filter_meds() and filter_hba1c().

The function should be able to process data with different time-stamps (date or week&year). Some users may have data on HONUGE/HONAAR (which week & year the service was billed by the clinic to the health insurance) and others may have data on the exact date the services was registered.

**Comment by signekb** [comment]
This is an outdated issue. I have created a new one based on the functions we have described in the functionality flow and will move the relevant information in this issue to that issue #90
